this commit fixes cicd build issue by creating a symbolic link at root of omni-xnft project `App.tsx` linking to `src/App.ts`. expo requires App be imported from root of the project directory.
 ModuleNotFoundError: Module not found: Error: Can't resolve '../../App' in '/home/runner/work/mrgn-ts/mrgn-ts/apps/omni-xnft/node_modules/expo'

this breaks cicd and generally triggers my ocd